FROM registry.access.redhat.com/ubi8/ubi

RUN dnf config-manager --add-repo=https://download.docker.com/linux/fedora/docker-ce.repo

# Install required packages and dependencies
RUN dnf install -y \
    docker-ce docker-ce-cli containerd.io \
    shadow-utils \
    python39 \
    python39-pip \
    python39-devel \
    procps-ng \
    iproute \
    iputils \
    && dnf clean all

# Create a non-root user
# RUN adduser -m -u 1001 appuser

WORKDIR /usr/src/app

# Copy source files and requirements
# COPY --chown=appuser:appuser src/* .
COPY src/setup.py .
COPY src/main.py .
COPY src/script.py .
COPY src/requirements.txt .

# Install Python dependencies
RUN pip3.9 install --user -r requirements.txt

# Add to PATH
ENV PATH="/root/.local/bin:${PATH}"

# Obfuscate
RUN pyarmor gen --enable-jit --assert-call --private script.py

# Switch to the non-root user 
# USER appuser

# Load tables and run (ensure iptables runs with sufficient privileges)
CMD ["bash", "-c", "python3 dist/script.py"]
